# Generated by Django 3.0.5 on 2020-04-06 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_from', models.DateField(null=True)),
                ('D_to', models.DateField(null=True)),
                ('detail', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseID', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('IDnum', models.CharField(max_length=20)),
                ('DoB', models.DateField(null=True)),
                ('DCC', models.DateField(null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Visit')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=20)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Visit')),
            ],
        ),
    ]
