# Generated by Django 3.0.5 on 2020-04-06 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='visit',
        ),
        migrations.AddField(
            model_name='visit',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Location'),
        ),
    ]
