# Generated by Django 3.0.5 on 2020-04-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20200407_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='detail',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
