# Generated by Django 3.0.5 on 2020-04-06 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200407_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='visit',
            name='detail',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='visit',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Location'),
        ),
    ]
