# Generated by Django 3.0.5 on 2020-04-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20200407_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='IDnum',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseID',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Location'),
        ),
    ]
