# Generated by Django 3.0.5 on 2020-04-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20200407_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='visit',
            new_name='visits',
        ),
    ]
