# Generated by Django 3.0.5 on 2020-04-07 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20200407_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Visit'),
        ),
        migrations.AddField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Patient'),
        ),
    ]
