# Generated by Django 3.0.5 on 2020-05-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0012_auto_20200407_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='DCC',
            field=models.DateField(null=True, verbose_name='Date Confirmed'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='DoB',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='IDnum',
            field=models.CharField(max_length=20, unique=True, verbose_name='ID NO.'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseID',
            field=models.IntegerField(unique=True, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Patient Name'),
        ),
    ]
