# Generated by Django 3.0.5 on 2020-05-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0013_auto_20200505_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='DCC',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='DoB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='IDnum',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseID',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
