# Generated by Django 3.0.5 on 2020-05-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_auto_20200505_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseID',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
